In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


# 1.Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [2]:
scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [3]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [4]:
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [5]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                      [10, 11, 12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

# 2.Find the shape, rank and size of the tensors you created in 1.

In [44]:
def get_info(tensor):
  print("\nDatatype: ", tensor.dtype,
      "\nDimensions (rank): ", tensor.ndim,
      "\nShape: ", tensor.shape,
      "\nSize: ", tf.size(tensor).numpy(),
      "\nElements along the first axis: ", tensor.shape[0],
      "\nElements along the last axis: ", tensor.shape[-1],
      "\nMaximum value: ", tf.reduce_max(tensor),
      "\nMinimum value: ", tf.reduce_min(tensor))

In [41]:
get_info(vector)


Datatype:  <dtype: 'int32'> 
Dimensions (rank):  1 
Shape:  (2,) 
Size:  2 
Elements along the first axis:  2 
Elements along the last axis:  2 
Maximum value:  tf.Tensor(10, shape=(), dtype=int32) 
Minimum value:  tf.Tensor(10, shape=(), dtype=int32)


In [42]:
get_info(matrix)


Datatype:  <dtype: 'int32'> 
Dimensions (rank):  2 
Shape:  (2, 3) 
Size:  6 
Elements along the first axis:  2 
Elements along the last axis:  3 
Maximum value:  tf.Tensor(6, shape=(), dtype=int32) 
Minimum value:  tf.Tensor(1, shape=(), dtype=int32)


In [28]:
get_info(tensor)


Datatype:  <dtype: 'int32'> 
Dimensions (rank):  3 
Shape:  (2, 2, 3) 
Size:  12 
Elements along the first axis:  2 
Elements along the last axis:  3 
Maximum value:  tf.Tensor(12, shape=(), dtype=int32) 
Minimum value:  tf.Tensor(1, shape=(), dtype=int32)


# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [29]:
tf.random.set_seed(42)
random_tensor_01 = tf.random.uniform(shape=(5, 300))
random_tensor_02 = tf.random.uniform(shape=(5, 300))

random_tensor_01, random_tensor_02

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

In [30]:
get_info(random_tensor_01), get_info(random_tensor_02)


Datatype:  <dtype: 'float32'> 
Dimensions (rank):  2 
Shape:  (5, 300) 
Size:  1500 
Elements along the first axis:  5 
Elements along the last axis:  300 
Maximum value:  tf.Tensor(0.99890864, shape=(), dtype=float32) 
Minimum value:  tf.Tensor(0.00019192696, shape=(), dtype=float32)

Datatype:  <dtype: 'float32'> 
Dimensions (rank):  2 
Shape:  (5, 300) 
Size:  1500 
Elements along the first axis:  5 
Elements along the last axis:  300 
Maximum value:  tf.Tensor(0.999833, shape=(), dtype=float32) 
Minimum value:  tf.Tensor(0.00032281876, shape=(), dtype=float32)


(None, None)

# 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [31]:
multiplied_tensor = tf.matmul(random_tensor_01, tf.transpose(random_tensor_02))
multiplied_tensor, get_info(multiplied_tensor)


Datatype:  <dtype: 'float32'> 
Dimensions (rank):  2 
Shape:  (5, 5) 
Size:  25 
Elements along the first axis:  5 
Elements along the last axis:  5 
Maximum value:  tf.Tensor(85.05689, shape=(), dtype=float32) 
Minimum value:  tf.Tensor(68.80438, shape=(), dtype=float32)


(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
        [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
        [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
        [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
        [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
       dtype=float32)>,
 None)

# 5. Multiply the two tensors you created in 3 using dot product.

In [32]:
dot_product_tensor = tf.tensordot(random_tensor_01, tf.transpose(random_tensor_02), axes=1)
dot_product_tensor, get_info(dot_product_tensor)


Datatype:  <dtype: 'float32'> 
Dimensions (rank):  2 
Shape:  (5, 5) 
Size:  25 
Elements along the first axis:  5 
Elements along the last axis:  5 
Maximum value:  tf.Tensor(85.05689, shape=(), dtype=float32) 
Minimum value:  tf.Tensor(68.80438, shape=(), dtype=float32)


(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
        [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
        [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
        [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
        [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
       dtype=float32)>,
 None)

# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [33]:
random_tensor = tf.random.uniform(shape=(224, 224, 3))
random_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

In [43]:
get_info(random_tensor)


Datatype:  <dtype: 'float32'> 
Dimensions (rank):  4 
Shape:  (1, 224, 224, 3) 
Size:  150528 
Elements along the first axis:  1 
Elements along the last axis:  3 
Maximum value:  tf.Tensor(0.9999902, shape=(), dtype=float32) 
Minimum value:  tf.Tensor(1.0967255e-05, shape=(), dtype=float32)


# 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [35]:
random_tensor = tf.random.uniform(shape=(1, 224 ,224 ,3))
get_info(random_tensor), random_tensor


Datatype:  <dtype: 'float32'> 
Dimensions (rank):  4 
Shape:  (1, 224, 224, 3) 
Size:  150528 
Elements along the first axis:  1 
Elements along the last axis:  3 
Maximum value:  tf.Tensor(0.9999902, shape=(), dtype=float32) 
Minimum value:  tf.Tensor(1.0967255e-05, shape=(), dtype=float32)


(None,
 <tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
          [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
          [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
          ...,
          [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
          [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
          [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],
 
         [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
          [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
          [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
          ...,
          [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
          [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
          [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],
 
         [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
          [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
          [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
          ...,
          [8.4168065e-01, 5.

In [37]:
squeezed_tensor = tf.squeeze(random_tensor)
get_info(squeezed_tensor), squeezed_tensor


Datatype:  <dtype: 'float32'> 
Dimensions (rank):  3 
Shape:  (224, 224, 3) 
Size:  150528 
Elements along the first axis:  224 
Elements along the last axis:  3 
Maximum value:  tf.Tensor(0.9999902, shape=(), dtype=float32) 
Minimum value:  tf.Tensor(1.0967255e-05, shape=(), dtype=float32)


(None,
 <tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
         [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
         [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
         ...,
         [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
         [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
         [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],
 
        [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
         [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
         [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
         ...,
         [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
         [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
         [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],
 
        [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
         [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
         [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
         ...,
         [8.4168065e-01, 5.0247252e-01, 2.8834987

# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [45]:
tensor = tf.constant([1, 5, 6, 7, 9, 2, 4, 6, 10, -10])
get_info(tensor), tensor


Datatype:  <dtype: 'int32'> 
Dimensions (rank):  1 
Shape:  (10,) 
Size:  10 
Elements along the first axis:  10 
Elements along the last axis:  10 
Maximum value:  tf.Tensor(10, shape=(), dtype=int32) 
Minimum value:  tf.Tensor(-10, shape=(), dtype=int32)


(None,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([  1,   5,   6,   7,   9,   2,   4,   6,  10, -10], dtype=int32)>)

In [47]:
# max value index
tf.argmax(tensor).numpy()

8

In [48]:
# min value index
tf.argmin(tensor).numpy()

9

# 10. One-hot encode the tensor you created in 9.

In [49]:
tf.one_hot(tf.cast(tensor, dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>