# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
array_01_dim = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
array_02_dim = np.array([[1, 2, 3],
                         [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
array_03_dim = np.array([[[1, 2, 3,],
                          [4, 5, 6]],
                         [[7, 8, 9],
                          [10, 11, 12]],
                         [[13, 14, 15],
                          [16, 17, 18]]])

array_01_dim.ndim, array_02_dim.ndim, array_03_dim.ndim

(1, 2, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
def get_array_info(array):
  print("Dimensions: ", array.ndim,
        "\nShape: ", array.shape,
        "\nDyype: ", array.dtype,
        "\nSize: ", array.size,
        "\nType: ", type(array))

get_array_info(array_01_dim)

Dimensions:  1 
Shape:  (3,) 
Dyype:  int64 
Size:  3 
Type:  <class 'numpy.ndarray'>


In [4]:
# Attributes of 2-dimensional array
get_array_info(array_02_dim)

Dimensions:  2 
Shape:  (2, 3) 
Dyype:  int64 
Size:  6 
Type:  <class 'numpy.ndarray'>


In [5]:
# Attributes of 3-dimensional array
get_array_info(array_03_dim)

Dimensions:  3 
Shape:  (3, 2, 3) 
Dyype:  int64 
Size:  18 
Type:  <class 'numpy.ndarray'>


In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df_from_array = pd.DataFrame(array_02_dim)
df_from_array

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones(shape=(10, 2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros = np.zeros(shape=(7, 2, 3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# Create an array within a range of 0 and 100 with step 3
array_0_to_100_step_03 = np.array(range(0, 100, 3))
array_0_to_100_step_03

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_random_0_10 = np.random.randint(10, size=(7, 2))
array_random_0_10

array([[2, 1],
       [5, 5],
       [7, 2],
       [1, 5],
       [9, 4],
       [1, 0],
       [1, 7]])

In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_random_0_to_1 = np.random.random((3, 5))
array_random_0_to_1

array([[0.35445455, 0.83751655, 0.57237511, 0.78426799, 0.02968855],
       [0.87142022, 0.80057945, 0.72849389, 0.89075163, 0.8453919 ],
       [0.21994067, 0.27275634, 0.03764034, 0.48993296, 0.02570242]])

In [26]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array_random_0_to_10 = np.random.randint(10, size=(4, 6))
array_random_0_to_10

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

**ANSWER**

The array has the same values no matter how many time I re-run the cell 'cos the random seed is static defined to 42

In [27]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array_random_1_to_10 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(array_random_1_to_10)

array([1, 2, 3, 4, 5, 7, 9])

In [28]:
# Find the 0'th index of the latest array you created
array_random_1_to_10[0]

array([9, 1, 3, 7, 4, 9, 3])

In [29]:
# Get the first 2 rows of latest array you created
array_random_1_to_10[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [30]:
# Get the first 2 values of the first 2 rows of the latest array
array_random_1_to_10[:2, :2]

array([[9, 1],
       [5, 3]])

In [31]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array_random_0_to_10 = np.random.randint(10, size=(3, 5))
array_ones = np.ones((3, 5))

array_random_0_to_10, array_ones

(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [32]:
# Add the two arrays together
array_random_0_to_10 + array_ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [33]:
# Create another array of ones of shape (5, 3)
array_ones = np.ones((5, 3))

In [34]:
# Try add the array of ones and the other most recent array together
array_random_0_to_10 + array_ones

ValueError: ignored

When you try the last cell, it produces an error. Why do think this is?

**A:** Because the shapes did not follow the rules of **dot product** of the inner values of the operation must be the same and the output must have the shape of the outer values

How would you fix it?

**A:** either transposing or reshaping one of the arrays/matrix

In [35]:
# Create another array of ones of shape (3, 5)
array_ones = np.ones((3, 5))

In [39]:
# Subtract the new array of ones from the other most recent array
array_random_0_to_10 - array_ones, array_random_0_to_10.shape, array_ones.shape

(array([[ 5.,  6.,  1., -1.,  2.],
        [ 0.,  6.,  2.,  0.,  4.],
        [ 4.,  8.,  2.,  4.,  0.]]),
 (3, 5),
 (3, 5))

In [40]:
# Multiply the ones array with the latest array
array_random_0_to_10 * array_ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [41]:
# Take the latest array to the power of 2 using '**'
array_random_0_to_10 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [42]:
# Do the same thing with np.square()
np.square(array_random_0_to_10)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [43]:
# Find the mean of the latest array using np.mean()
np.mean(array_random_0_to_10)

3.8666666666666667

In [44]:
# Find the maximum of the latest array using np.max()
np.max(array_random_0_to_10)

9

In [45]:
# Find the minimum of the latest array using np.min()
np.min(array_random_0_to_10)

0

In [46]:
# Find the standard deviation of the latest array
np.std(array_random_0_10)

2.7180425129200643

In [47]:
# Find the variance of the latest array
np.var(array_random_0_to_10)

6.648888888888889

In [48]:
# Reshape the latest array to (3, 5, 1)
array_random_0_to_10.reshape(3, 5, 1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [49]:
# Transpose the latest array
array_random_0_to_10.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

**A:** It "flips" the axes

In [50]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_random_int_01 = np.random.randint(0, 10, size=(3, 3))
array_random_int_02 = np.random.randint(0, 10, size=(3, 2))

array_random_int_01, array_random_int_02

(array([[9, 1, 9],
        [3, 7, 6],
        [8, 7, 4]]),
 array([[1, 4],
        [7, 9],
        [8, 8]]))

In [52]:
# Perform a dot product on the two newest arrays you created
np.dot(array_random_int_01, array_random_int_02)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [56]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_random_int_01 = np.random.randint(0, 10, size=(4, 3))
array_random_int_02 = np.random.randint(0, 10, size=(4, 3))

array_random_int_01, array_random_int_02

(array([[8, 7, 1],
        [0, 6, 6],
        [7, 4, 2],
        [7, 5, 2]]),
 array([[0, 2, 4],
        [2, 0, 4],
        [9, 6, 6],
        [8, 9, 9]]))

In [57]:
# Perform a dot product on the two newest arrays you created
np.dot(array_random_int_01, array_random_int_02)

ValueError: ignored

It doesn't work. How would you fix it?

**A:** either transposing or reshaping one of the arrays/matrix

In [58]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(array_random_int_01, array_random_int_02.T)

array([[ 18,  20, 120, 136],
       [ 36,  24,  72, 108],
       [ 16,  22,  99, 110],
       [ 18,  22, 105, 119]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [59]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_random_int_01 = np.random.randint(0, 10, size=(4, 3))
array_random_int_02 = np.random.randint(0, 10, size=(4, 3))

array_random_int_01, array_random_int_02

(array([[2, 6, 0],
        [3, 3, 4],
        [6, 6, 3],
        [6, 2, 5]]),
 array([[1, 9, 8],
        [4, 5, 3],
        [9, 6, 8],
        [6, 0, 0]]))

In [60]:
# Compare the two arrays with '>'
array_random_int_01 > array_random_int_02

array([[ True, False, False],
       [False, False,  True],
       [False, False, False],
       [False,  True,  True]])

What happens when you compare the arrays with `>`?

**A:** It compares each value of the arrays at the same index

In [61]:
# Compare the two arrays with '>='
array_random_int_01 >= array_random_int_02

array([[ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True,  True,  True]])

In [63]:
# Find which elements of the first array are greater than 7
array_random_int_01 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [64]:
# Which parts of each array are equal? (try using '==')
array_random_int_01 == 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [65]:
# Sort one of the arrays you just created in ascending order
np.sort(array_random_int_01)

array([[0, 2, 6],
       [3, 3, 4],
       [3, 6, 6],
       [2, 5, 6]])

In [67]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_random_int_01)

array([[2, 0, 1],
       [0, 1, 2],
       [2, 0, 1],
       [1, 2, 0]])

In [68]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_random_int_01)

1

In [70]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_random_int_01)

2

In [71]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_random_int_02, axis=1)

array([1, 1, 0, 0])

In [72]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array_random_int_02, axis=0)

array([0, 3, 3])

In [73]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-0.39210815, -1.46351495,  0.29612028,  0.26105527,  0.00511346],
       [-0.23458713, -1.41537074, -0.42064532, -0.34271452, -0.80227727],
       [-0.16128571,  0.40405086,  1.8861859 ,  0.17457781,  0.25755039]])

In [74]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.